name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl
        curl -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        cargo install lychee

    - name: Run Lychee on multiple file types
      run: |
        find . -type f \( -name "*.md" -o -name "*.json" -o -name "*.js" -o -name "*.yaml" -o -name "*.xml" -o -name "*.jsp" -o -name "*.htm" -o -name "*.html" -o -name "*.properties" \) | while read -r file; do
          echo "Checking $file"
          lychee --verbose "$file"
        done
