name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl
        curl -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        cargo install lychee

    - name: Run Lychee to check for broken links
      run: |
        lychee --verbose --format markdown .
